### ISSUE TITLE
Possibility to ban all routes and enable one by one

### ISSUE THREAD

**Issue by franciscosantamaria** [artprima/prometheus-metrics-bundle#9]
Hi, I have one question related to this bundle:

* I've checked the code and didn't find how can I disable all routes except the ones I want. I mean, instead of a white-list strategy, maybe add the possibility to do the opposite, enabling only the routes you want.

One first approach is adding 2 new optional parameters in the _prometheus_metrics.yaml_ file:

- **exclude_all_routes**  with a boolean value.
- **enabled_routes** with a list of enabled routes.

What do you think? 
If you agree, I can try to code this feature and create a PR.

PS: Can I do this without any change in the bundle and avoid to add a full list of my application routes, to just metric only one or two routes?

BTW thank you for your free time spent it in this bundle.

**Comment by denisvmedia** [comment]
Thanks for your proposal @franciscosantamaria , it totally makes sense. And yeah, currently, it's not possible in the bundle. The only solution now is to override the RequestCounterListener service. However, it's a bit hacky.

A whitelist strategy can be easily added in addition to a blacklist strategy that we already have. If you are fine with providing a PR, I would happily accept it :) So, I propose this behavior in order not to break the code that already relies on the current one:

- we keep the blacklist strategy where it is now and do not change it
- we add a new option: `only_routes`
- if `only_routes` is empty we work completely the same way like now
- if `only_routes` is set, we always check it after the blacklist check (so it is possible to combine both options, even though it doesn't make much sense now; it may however be later extended to route name templates instead of full concrete names, and in this case blacklist + whitelist could work together very well)

What do you think? If you agree, I'd be happy to see a PR :) If not, let's discuss it further.
